### ISSUE TITLE
Broadcast/merge behavior changed from version 2.3.0 to version 2.4.6

### ISSUE THREAD

**Issue by nikiforo** [typelevel/fs2#2191] opened 2020-12-23 21:25 UTC
Consider this example:
```scala
object BroadcastMerge extends IOApp {

  implicit class partitionEitherOps[F[_], O](val stream: Stream[F, O]) {

    def partitionEither[L, R](f: O => Either[L,R])(implicit c: Concurrent[F]): Stream[F, (Stream[F, L], Stream[F, R])] =
      for {
        broadIn <- stream.map(f).through(Broadcast(2)).take(2).foldMap(List(_))
        List(in1, in2) = broadIn
        ls = in1.flatMap(_.fold(Stream.emit, _ => Stream.empty))
        rs = in2.flatMap(_.fold(_ => Stream.empty, Stream.emit))
      } yield (ls, rs)
  }

  def run(args: List[String]): IO[ExitCode] = {
    val stream = Stream(1,2,3,4,5,6).covary[IO]

    val results =
      for {
        tuple <- stream.partitionEither(el => if(el % 2 == 0) el.asLeft else el.asRight)
        (s1, s2) = tuple
        r <- s1.map(_ * 10).merge(s2.map(_ * 100))
      } yield r
    
    for {
      list <- results.compile.toList
      _ <- IO.delay(println(Set(20, 40, 60) ++ Set(100, 300, 500) == list.toSet))
    } yield ExitCode.Success
  }
}
```

While it outputs "true" to console prior to and including commit 099a3a1a, it outputs "false" starting from commit 8a7a13f4

This is bisect output:
```
8a7a13f4200648e9ec8a2e48f2d8641457e4e212 is the first bad commit
commit 8a7a13f4200648e9ec8a2e48f2d8641457e4e212
Author: Michael Pilquist <mpilquist@gmail.com>
Date:   Fri Jun 5 12:45:35 2020 -0400

    Fix scope leak with Stream.retry and in general, with pulls that do not consume all elements from source

:040000 040000 08176432576c76388ef2e6893039d63e8cd56fb7 ec2a4ee774b6b86d7216668793ad201fe45d2f5c
```

This is a link to commit: https://github.com/typelevel/fs2/commit/8a7a13f4200648e9ec8a2e48f2d8641457e4e212

I'm not sure whether this should be considered a bug

**Comment by mpilquist** [comment] 2020-12-24 00:01
This gives the desired behavior:

```scala
    def partitionEither[L, R](f: O => Either[L,R])(implicit c: Concurrent[F]): Stream[F, (Stream[F, L], Stream[F, R])] =
      stream.map(f).through(Broadcast(2)).take(2).pull.unconsN(2).flatMap {
        case Some((hd, _)) => 
          val lefts = hd(0).flatMap(_.fold(Stream.emit, _ => Stream.empty))
          val rights = hd(1).flatMap(_.fold(_ => Stream.empty, Stream.emit))
          Pull.output1(lefts -> rights)
        case None => Pull.done
      }.stream
```

**Comment by mpilquist** [comment] 2020-12-24 00:55
This also gives the desired behavior and is more idiomatic in my opinion:

```scala
    def partitionEither[L, R](f: O => Either[L,R])(implicit c: Concurrent[F]): Stream[F, (Stream[F, L], Stream[F, R])] =
      Stream.eval((Queue.bounded[F, Option[L]](100), Queue.bounded[F, Option[R]](100)).tupled).flatMap { case (lq, rq) =>
        val producer = stream.map(f).evalMap {
          case Left(l) => lq.enqueue1(Some(l))
          case Right(r) => rq.enqueue1(Some(r))
        } ++ Stream.eval(lq.enqueue1(None) >> rq.enqueue1(None))
        Stream.emit(lq.dequeue.unNoneTerminate, rq.dequeue.unNoneTerminate).concurrently(producer)
      }
```

**Comment by mpilquist** [comment] 2020-12-24 02:05
Here's a minimal change to original code which restores expected behavior:

```scala
    def partitionEither[L, R](f: O => Either[L,R])(implicit c: Concurrent[F]): Stream[F, (Stream[F, L], Stream[F, R])] =
      for {
        broadIn <- stream.map(f).through(Broadcast(2)).pull.take(2).void.streamNoScope.foldMap(List(_))
        List(in1, in2) = broadIn
        ls = in1.flatMap(_.fold(Stream.emit, _ => Stream.empty))
        rs = in2.flatMap(_.fold(_ => Stream.empty, Stream.emit))
      } yield (ls, rs)
```

Instead of `.take(2)`, we use `.pull.take(2).void.streamNoScope` -- that is, we explicitly avoid creating a scope when taking. I think we should change `take` and similar operations (e.g. takeWhile/takeThrough/drop/...) to use `.streamNoScope` instead of `.stream` like that do now. Thoughts?

**Comment by SystemFw** [comment] 2020-12-24 02:06
I have a vague memory that not inserting a scope after `take` caused bugs, and we went back and forth a couple of times

**Comment by mpilquist** [comment] 2020-12-24 03:03
@SystemFw Hm, yeah, I suppose `take` is a prototypical example of a "pull that does not consume all elements from the source".

**Comment by mpilquist** [comment] 2020-12-29 01:13
This works as well (with suitable adjustments to call site):

```scala

    def partitionEither[X](f: O => Either[X, X])(implicit c: Concurrent[F]): Stream[F, Stream[F, X]] =
      stream.map(f).through(Broadcast(2)).take(2).zipWithIndex.map { case (s, idx) =>
        if (idx == 0) s.flatMap(_.fold(Stream.emit, _ => Stream.empty))
        else s.flatMap(_.fold(_ => Stream.empty, Stream.emit))
      }
```

The combination of `take(n).fold` is the problematic pattern here, where the yielded streams don't "subscribe" to the `PubSub` until after it's passed out of scope. To avoid this, either use `.pull.take(n).void.streamNoScope` or avoid `fold` and use something like the above. Closing this as not a bug though it shows the weakness of the scope model we use.

**Closed by mpilquist** 2020-12-29 01:13 UTC
